pipeline {
    environment {
        DOCKERHUB_CRED = credentials("DockerSid")
    }
    agent any
    tools {nodejs "NODEJS"} 
    stages {
        stage("Stage 1: Git Clone") {
            steps {
                git credentialsId: 'GitHubSid', url: 'https://github.com/SiddharthChauhan303/SPE-Project-kub-hpa.git', branch: 'main'
            }
        }
        stage('Initialize') {
            steps {
                sh "python3 -m venv venv"
                sh '. venv/bin/activate &&  pip3 install -r model/requirements.txt'
            }
        }

        stage('Preprocess Data') {
            steps {
                sh '. venv/bin/activate &&  python3 model/preprocess_data.py model/dataset/ADANIPOWER.csv'
            }
        }

        stage('Train and Backtest Model') {
            steps {
                sh '. venv/bin/activate && python3 model/train_model.py model/dataset/ADANIPOWER.csv model/weights'
            }
        }
        stage('Unit Testing') {
            steps {
                script {
                    // Run model evaluation script
                    sh ". venv/bin/activate && pytest model/test_model.py"
                }
            }
        }
        stage("Build Docker Image"){
                    steps{
                        sh "docker build -t siddharth303/model_jenkins:latest model"
                    }
                }

        stage("Push Docker Image to Dockerhub"){
            steps{
                sh 'echo $DOCKERHUB_CRED_PSW | docker login -u $DOCKERHUB_CRED_USR --password-stdin'
                sh "docker push siddharth303/model_jenkins:latest"
            }
        }
    }
}