pipeline {
    environment {
        DOCKERHUB_CRED = credentials("DockerCredentials")
    }
    agent any
    tools {nodejs "NODEJS"} 
    stages {
        stage("Stage 1: Git Clone") {
            steps {
                // sh "rm -r SPE-FInal-Project"
                // sh "git clone https://github.com/Kushal7551/SPE-FInal-Project.git"
                git credentialsId: 'GitHub-Credentials', url: 'https://github.com/kushal7551/SPE-FInal-Project.git', branch: 'main'
                // sh "ls"
            }
        }
        stage('Initialize') {
            steps {
                sh "python3 -m venv venv"
                sh '. venv/bin/activate &&  pip3 install -r backend/StockTradingRL/requirements.txt'
            }
        }

        stage('Preprocess Data') {
            steps {
                sh '. venv/bin/activate &&  python3 backend/StockTradingRL/preprocess_data.py backend/StockTradingRL/ADANIPOWER.csv'
            }
        }

        stage('Train and Backtest Model') {
            steps {
                sh '. venv/bin/activate && python3 backend/StockTradingRL/train_and_backtest.py backend/StockTradingRL/ADANIPOWER.csv'
            }
        }
        stage('Unit Testing') {
            steps {
                script {
                    // Run model evaluation script
                    sh ". venv/bin/activate && pytest backend/StockTradingRL/test_stocktradingRL.py"
                }
            }
        }
    }
}
