pipeline {
    environment {
        DOCKERHUB_CRED = credentials("DockerSid")
    }
    agent any
    tools {nodejs "NODEJS"} 
    stages {
        stage("Git Clone") {
            steps {
                git credentialsId: 'GitHubSid', url: 'https://github.com/SiddharthChauhan303/SPE-Project-kub-hpa.git', branch: 'main'
            }
        }


        stage("Frontend Testing") {
            steps {
                sh '''
                cd frontend
                npm install
                '''
            }
        }

        stage("Creating Docker Image for frontend") {
            steps {
                sh '''
                cd frontend
                ls
                docker build -t siddharth303/frontend_jenkins:latest .
                '''
            }
        }


        stage("Push Frontend Docker Image") {
            steps {
                sh '''
                docker login -u ${DOCKERHUB_CRED_USR} -p ${DOCKERHUB_CRED_PSW}
                docker push siddharth303/frontend_jenkins:latest
                '''
            }
        }
    }
}